version: 2

sources:
  - name: silverscreen
    database: SilverScreen
    schema: PUBLIC
    tables:
      - name: movie_catalogue
        description: "Detaillierte Informationen über Filme, die 2024 veröffentlicht und von Silver Screen gemietet wurden."
        columns:
          - name: movie_id
            description: "Eindeutiger Bezeichner für jeden Film."
          - name: movie_title
            description: "Der Titel des Films."
          - name: release_date
            description: "Das offizielle Veröffentlichungsdatum des Films im Format YYYY-MM-DD."
          - name: genre
            description: "Das Genre des Films."
          - name: country
            description: "Das Produktionsland des Films."
          - name: studio
            description: "Das Produktionsstudio des Films."
          - name: budget
            description: "Das Produktionsbudget des Films."
          - name: director
            description: "Der Regisseur des Films."
          - name: rating
            description: "Die Altersfreigabe des Films."
          - name: minutes
            description: "Die Laufzeit des Films in Minuten."

      - name: invoices
        description: "Rechnungen für die Vorführung eines bestimmten Films an verschiedenen Kinostandorten."
        columns:
          - name: movie_id
            description: "Eindeutiger Bezeichner für jeden Film."
          - name: invoice_id
            description: "Eindeutiger Bezeichner für jede Rechnung."
          - name: month
            description: "Der Monat, in dem die Rechnung ausgestellt wurde."
          - name: location_id
            description: "Der Bezeichner des Kinostandorts."
          - name: Studio
            description: "Das Produktionsstudio."
          - name: Release_Date
            description: "Das offizielle Veröffentlichungsdatum des Films."
          - name: Weekly_price
            description: "Der wöchentliche Preis für die Vorführung des Films."
          - name: Total_invoice_sum
            description: "Die Gesamtsumme der Rechnung für die Woche."

      - name: nj_001
        description: "Transaktionsdaten vom Standort Nr. 1."
        columns:
          - name: timestamp
            description: "Datum und Uhrzeit der Transaktion."
          - name: transaction_id
            description: "Eindeutiger Bezeichner für jede Transaktion."
          - name: movie_id
            description: "Eindeutiger Bezeichner für den Film."
          - name: ticket_amount
            description: "Anzahl der gekauften Tickets."
          - name: price
            description: "Preis pro Ticket."
          - name: transaction_total
            description: "Gesamtbetrag der Transaktion."
          - name: is_discounted
            description: "Gibt an, ob ein Rabatt gewährt wurde."
          - name: is_3d
            description: "Gibt an, ob der Film in 3D war."

      - name: nj_002
        description: "Tägliche Verkaufsinformationen vom Standort Nr. 2."
        columns:
          - name: date
            description: "Datum der Ticketverkäufe."
          - name: movie_id
            description: "Eindeutiger Bezeichner für den Film."
          - name: ticket_amount
            description: "Anzahl der an diesem Tag verkauften Tickets."
          - name: ticket_price
            description: "Preis pro an diesem Tag verkauftem Ticket."
          - name: total_earned
            description: "Gesamteinnahmen aus Ticketverkäufen an diesem Datum."

      - name: nj_003
        description: "Einzelne Einkäufe vom Standort Nr. 3 (Tickets, Snacks, Getränke)."
        columns:
          - name: timestamp
            description: "Datum und Uhrzeit der Transaktion."
          - name: transaction_id
            description: "Eindeutiger Bezeichner für jede Transaktion."
          - name: product_type
            description: "Art des Produkts (Ticket, Getränk, Snack etc.)."
          - name: details
            description: "Für Tickets die movie_id, ansonsten leer."
          - name: amount
            description: "Menge des gekauften Produkts."
          - name: price
            description: "Preis pro Einheit des Produkts."
          - name: total_value
            description: "Gesamtwert der Transaktion."

