version: 2

sources:
  - name: silverscreen 
    description: "Rohdaten für die Silver Screen Kinoanalyse."
    database: SILVERSCREEN
    schema: PUBLIC 
    tables:
      - name: movie_catalogue
        description: "Enthält detaillierte Informationen über Filme, die 2024 veröffentlicht und von 'Silver Screen' gemietet wurden."
        columns:
          - name: movie_id
            description: "Eindeutiger Identifikator für jeden Film."
            tests:
              - unique
              - not_null
          - name: movie_title
            description: "Der Titel des Films."
          - name: release_date
            description: "Das offizielle Erscheinungsdatum des Films im YYYY-MM-DD-Format."
          - name: genre
            description: "Das Genre des Films."
          - name: country
            description: "Das Produktionsland des Films."
          - name: studio
            description: "Das Produktionsstudio, das für den Film verantwortlich ist."
          - name: budget
            description: "Das Produktionsbudget des Films in Dollar."
          - name: director
            description: "Der Regisseur des Films."
          - name: rating
            description: "Die Altersfreigabe des Films."
          - name: minutes
            description: "Die Laufzeit des Films in Minuten."

      - name: invoices
        description: "Rechnungen für die Vorführung eines bestimmten Films an verschiedenen Standorten."
        columns:
          - name: movie_id
            description: "Eindeutiger Identifikator für jeden Film."
          - name: invoice_id
            description: "Eindeutiger Identifikator für jede Rechnung."
            tests:
              - unique
              - not_null
          - name: month
            description: "Der Monat, in dem die Rechnung ausgestellt wurde, im YYYY-MM-DD-Format."
          - name: location_id
            description: "Der Identifikator des Kinostandorts."
          - name: Studio
            description: "Das Produktionsstudio des Films."
          - name: Release_Date
            description: "Das offizielle Erscheinungsdatum des Films."
          - name: Weekly_price
            description: "Der wöchentliche Preis für die Vorführung des Films."
          - name: Total_invoice_sum
            description: "Die Gesamtsumme der Rechnung für die Woche."

      - name: nj_001
        description: "Detaillierte Transaktionsdaten vom Standort NJ_001."
        columns:
          - name: timestamp
            description: "Datum und Uhrzeit der Transaktion."
          - name: transaction_id
            description: "Eindeutiger Identifikator für jede Transaktion."
            tests:
              - unique
              - not_null
          - name: movie_id
            description: "Identifikator für den angesehenen Film."
          - name: ticket_amount
            description: "Anzahl der in dieser Transaktion gekauften Tickets."
          - name: price
            description: "Der Preis pro Ticket für die Transaktion."
          - name: transaction_total
            description: "Gesamtbetrag der Transaktion."
          - name: is_discounted
            description: "Ein boolescher Wert, der angibt, ob ein Rabatt gewährt wurde."
          - name: is_3D
            description: "Ein boolescher Wert, der angibt, ob der Film in 3D gezeigt wurde."

      - name: nj_002
        description: "Tägliche aggregierte Verkaufsdaten vom Standort NJ_002."
        columns:
          - name: date
            description: "Das Datum der Ticketverkäufe."
          - name: movie_id
            description: "Identifikator für den verkauften Film."
          - name: ticket_amount
            description: "Anzahl der an diesem Tag verkauften Tickets."
          - name: ticket_price
            description: "Der Preis pro verkauftem Ticket an diesem Tag."
          - name: total_earned
            description: "Gesamteinnahmen aus Ticketverkäufen an diesem Datum."

      - name: nj_003
        description: "Einzelne Kauftransaktionen vom Standort NJ_003, einschließlich Tickets und anderer Produkte."
        columns:
          - name: timestamp
            description: "Datum und Uhrzeit der Transaktion."
          - name: transaction_id
            description: "Eindeutiger Identifikator für jede Transaktion."
            tests:
              - unique
              - not_null
          - name: product_type
            description: "Die Art des in der Transaktion enthaltenen Produkts (z. B. Ticket, Getränk, Snack)."
          - name: details
            description: "Für Tickets die movie_id."
          - name: amount
            description: "Die Menge des gekauften Produkts."
          - name: price
            description: "Der Preis pro Produkteinheit."
          - name: total_value
            description: "Der in der Transaktion ausgegebene Gesamtbetrag."
